---
- name: "prem : config : Copy infra ssh private key {{r_libre_userconfig_dir}}/infra-id_rsa to {{config_libre.directory.conf}}/infra-id_rsa"
  copy:
    src: "{{r_libre_userconfig_dir}}/infra-id_rsa"
    dest: "{{config_libre.directory.conf}}/infra-id_rsa"
    mode: 0644
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"
- name: "prem : config : Copy infra ssh public key {{r_libre_userconfig_dir}}/infra-id_rsa.pub to {{config_libre.directory.conf}}/infra-id_rsa.pub"
  copy:
    src: "{{r_libre_userconfig_dir}}/infra-id_rsa.pub"
    dest: "{{config_libre.directory.conf}}/infra-id_rsa.pub"
    mode: 0644
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"
- name: "prem : config : Generate infrastructure config file {{ config_libre.directory.conf }}/{{ r_infra_config_file }}"
  template:
    src: templates/libre-infra.j2
    dest: "{{ config_libre.directory.conf }}/{{ r_infra_config_file }}"
    mode: 0664
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"
  become: yes
- name: "prem : config : Succesfull config for On-Premise infrastructure"
  debug:
    msg:
      - " "
      - "On-Premise infrastructure for session {{ libre_session.id }} delivering course {{ libre_session.course }}"
      - "is now configured. You can continue this process by :"
      - " "
      - "1. Review classroom infrastructure configuration file {{config_libre.directory.conf}}/{{ r_infra_config_file }}"
      - "2. Start provisionning infrastructure by executing the following command :"
      - "   $ libre-infra prem provision"
      - " "
      - " Have an happy training ;)"
      - " "
