---
# Update tasks
- name: "update : Start updating repository"
  include_role:
    name: repository
    tasks_from: "update.yml"
- name: "update : Get previous report data"
  set_fact:
    previous_report: "{{ lookup('file', r_libre_tmp + '/' + r_repository_tmpfile) | default('') }}"
  delegate_to: localhost
  become: no
- name: "update : Generate instructor update report at {{ r_libre_tmp }}/{{ r_repository_tmpfile }}"
  template:
    src: templates/libre_report-update.j2
    dest: "{{ r_libre_tmp }}/{{ r_repository_tmpfile }}"
    mode: 0664
  delegate_to: localhost
  become: no
