---
- name: "aws : config : Set spare lab-environement to {% if 'classroomInfra' in libre_course and 'spare' in libre_course.classroomInfra %}{{(libre_course.classroomInfra.spare|int|default(1))}}{% else %}1{% endif %}"
  set_fact:
    spare_nb: "{% if 'classroomInfra' in libre_course and 'spare' in libre_course.classroomInfra %}{{(libre_course.classroomInfra.spare|int|default(1))}}{% else %}1{% endif %}"
- name: "aws : config : Set environements_nb to create to {{ (libre_session.students|length|default(0))+ (spare_nb|int) + 1 }}"
  set_fact:
    libre_infra: "{{ libre_infra|combine({'ec2': {'environements_nb': (libre_session.students|length|default(0))+ (spare_nb|int) + 1 }}, recursive=True) }}"

- name: "aws : config : Configure AWS access key"
  pause:
   prompt: "What is your AWS Access key ?"
  register: aws_access_key
- name: "aws : config : Register access_key in libre_infra fact"
  set_fact:
    libre_infra: "{{ libre_infra|combine({'auth': {'access_key': aws_access_key.user_input }}, recursive=True) }}"
  when: aws_access_key.user_input is defined
- name: "aws : config : Configure AWS access key"
  pause:
   prompt: "What is your AWS Access key ?"
  register: aws_secret_key
- name: "aws : config : Register secret_key in libre_infra fact"
  set_fact:
    libre_infra: "{{ libre_infra|combine({'auth': {'secret_key': aws_secret_key.user_input }}, recursive=True) }}"
  when: aws_secret_key.user_input is defined

- name: "aws : config : Generate ssh keypairs in {{config_libre.directory.conf}}"
  openssh_keypair:
    path: "{{config_libre.directory.conf}}/{{ user2 }}-id_rsa"
    size: 4096
    type: rsa
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"
  loop:
    - instructor
    - student
  loop_control:
    loop_var: user2
    label: "{{ user2 }}"
- name: "aws : config : Copy infra ssh private key {{r_libre_userconfig_dir}}/infra-id_rsa to {{config_libre.directory.conf}}/infra-id_rsa"
  copy:
    src: "{{r_libre_userconfig_dir}}/infra-id_rsa"
    dest: "{{config_libre.directory.conf}}/infra-id_rsa"
    mode: 0644
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"
- name: "aws : config : Copy infra ssh public key {{r_libre_userconfig_dir}}/infra-id_rsa.pub to {{config_libre.directory.conf}}/infra-id_rsa.pub"
  copy:
    src: "{{r_libre_userconfig_dir}}/infra-id_rsa.pub"
    dest: "{{config_libre.directory.conf}}/infra-id_rsa.pub"
    mode: 0644
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"

- name: "aws : config : Generate infrastructure config file {{ config_libre.directory.conf }}/{{ r_infra_config_file }}"
  template:
    src: templates/libre-infra.j2
    dest: "{{ config_libre.directory.conf }}/{{ r_infra_config_file }}"
    mode: 0664
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"

- name: "aws : config : Succesfull config for Public-Cloud AWS infrastructure"
  debug:
    msg:
      - " "
      - "Public-Cloud AWS infrastructure for session {{ libre_session.id }} delivering course {{ libre_session.course }}"
      - "is now configured. You can continue this process by :"
      - " "
      - "1. Review classroom infrastructure configuration file {{config_libre.directory.conf}}/{{ r_infra_config_file }}"
      - "2. Start provisionning infrastructure by executing the following command :"
      - "   $ libre-infra aws provision"
      - " "
      - " Have an happy training ;)"
      - " "
