---
- name: "aws : provision-post-instructor : Change hostname for instructor-{{libre_session.id}}"
  hostname:
    name: "instructor-{{libre_session.id}}"
  become: yes
  when: inventory_hostname in groups.instructor
- name: "aws : provision-post-instructor : Log instructor post-provision action"
  include_role:
    name: libre
    tasks_from: lib/log
  vars:
    log_name: "AWS infrastructure is Post-provisionned on instructor"
    log_component: infra-aws
    log_action: post-provision AWS infrastructure on instructor