---
- name: "aws : provision-post-post : student {{ student.id}} : Create the libre user group {{ r_libre_group }} in students nodes"
  group:
    name: "{{ r_libre_group }}"
    state: present
  delegate_to: "{{node.name}}-env{{student.workstation|default('0')}}.{{ libre_session.id }}.{{ libre_infra.route53.domain }}"
  loop: "{{ classroom }}"
  loop_control:
    loop_var: node
    label: "{{ node.name }}"
- name: "aws : provision-post-post : student {{ student.id}} : Allow '{{ r_libre_group }}' group to have passwordless sudo"
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%{{ r_libre_group }}'
    line: '%{{ r_libre_group }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  delegate_to: "{{node.name}}-env{{student.workstation|default('0')}}.{{ libre_session.id }}.{{ libre_infra.route53.domain }}"
  loop: "{{ classroom }}"
  loop_control:
    loop_var: node
    label: "{{ node.name }}"
- name: "aws : provision-post-post : student {{ student.id }} : Create the {{r_infra_user_student}} user in students nodes"
  user:
    name: "{{ r_infra_user_student }}"
    comment: "LIBRE {{ r_infra_user_student }}"
    groups: "{{ r_libre_group }}"
    password: "{{ r_infra_user_student | password_hash('sha512') }}"
    state: present
  delegate_to: "{{node.name}}-env{{student.workstation|default('0')}}.{{ libre_session.id }}.{{ libre_infra.route53.domain }}"
  loop: "{{ classroom }}"
  loop_control:
    loop_var: node
    label: "{{ node.name }}"
- name: "aws : provision-post-post : student {{ student.id}} : Authorize infrastructure SSH key for root in students nodes"
  authorized_key:
    user: "root"
    state: present
    key: "{{ lookup('file', config_libre.directory.conf + '/infra-id_rsa.pub') }}"
  delegate_to: "{{node.name}}-env{{student.workstation|default('0')}}.{{ libre_session.id }}.{{ libre_infra.route53.domain }}"
  loop: "{{ classroom }}"
  loop_control:
    loop_var: node
    label: "{{ node.name }}"
- name: "aws : provision-post-post : student {{ student.id}} : Authorize instructor SSH key for root in students nodes"
  authorized_key:
    user: "root"
    state: present
    key: "{{ lookup('file', config_libre.directory.conf + '/instructor-id_rsa.pub') }}"
  delegate_to: "{{node.name}}-env{{student.workstation|default('0')}}.{{ libre_session.id }}.{{ libre_infra.route53.domain }}"
  loop: "{{ classroom }}"
  loop_control:
    loop_var: node
    label: "{{ node.name }}"
- name: "aws : provision-post-post : student {{ student.id}} : Authorize instructor SSH key for {{ r_infra_user_instructor }} in students nodes"
  authorized_key:
    user: "{{ r_infra_user_instructor }}"
    state: present
    key: "{{ lookup('file', config_libre.directory.conf + '/instructor-id_rsa.pub') }}"
  delegate_to: "workstation-env{{student.workstation|default('0')}}.{{ libre_session.id }}.{{ libre_infra.route53.domain }}"
- name: "aws : provision-post-post : student {{ student.id}} : Authorize instructor SSH key for {{ r_infra_user_student }} in students nodes"
  authorized_key:
    user: "{{ r_infra_user_student }}"
    state: present
    key: "{{ lookup('file', config_libre.directory.conf + '/instructor-id_rsa.pub') }}"
  delegate_to: "{{node.name}}-env{{student.workstation|default('0')}}.{{ libre_session.id }}.{{ libre_infra.route53.domain }}"
  loop: "{{ classroom }}"
  loop_control:
    loop_var: node
    label: "{{ node.name }}"
- name: "aws : provision-post-post : student {{ student.id}} : Authorize student SSH key for {{ r_infra_user_student }} in students nodes"
  authorized_key:
    user: "{{ r_infra_user_student }}"
    state: present
    key: "{{ lookup('file', config_libre.directory.conf + '/student-id_rsa.pub') }}"
  delegate_to: "{{node.name}}-env{{student.workstation|default('0')}}.{{ libre_session.id }}.{{ libre_infra.route53.domain }}"
  loop: "{{ classroom }}"
  loop_control:
    loop_var: node
    label: "{{ node.name }}"
- name: "aws : provision-post-post : student {{ student.id}} : Ensure student SSH public key is present for {{ r_infra_user_student }}"
  copy:
    src: "{{ config_libre.directory.conf }}/student-id_rsa.pub"
    dest: "/home/{{ r_infra_user_student }}/.ssh/id_rsa.pub"
    mode: 0600
    owner: "{{ r_infra_user_student }}"
    group: "{{ r_infra_usergroup }}"
  delegate_to: "{{node.name}}-env{{student.workstation|default('0')}}.{{ libre_session.id }}.{{ libre_infra.route53.domain }}"
  loop: "{{ classroom }}"
  loop_control:
    loop_var: node
    label: "{{ node.name }}"
- name: "aws : provision-post-post : student {{ student.id}} : Ensure student SSH private key is present for {{ r_infra_user_student }}"
  copy:
    src: "{{ config_libre.directory.conf }}/student-id_rsa"
    dest: "/home/{{ r_infra_user_student }}/.ssh/id_rsa"
    mode: 0600
    owner: "{{ r_infra_user_student }}"
    group: "{{ r_infra_usergroup }}"
  delegate_to: "{{node.name}}-env{{student.workstation|default('0')}}.{{ libre_session.id }}.{{ libre_infra.route53.domain }}"
  loop: "{{ classroom }}"
  loop_control:
    loop_var: node
    label: "{{ node.name }}"
- name: "aws : provision-post-post : student {{ student.id}} : Ensure student SSH public key is present for root"
  copy:
    src: "{{ config_libre.directory.conf }}/student-id_rsa.pub"
    dest: "/root/.ssh/id_rsa.pub"
    mode: 0600
    owner: "root"
  delegate_to: "{{node.name}}-env{{student.workstation|default('0')}}.{{ libre_session.id }}.{{ libre_infra.route53.domain }}"
  loop: "{{ classroom }}"
  loop_control:
    loop_var: node
    label: "{{ node.name }}"
- name: "aws : provision-post-post : student {{ student.id}} : Ensure student SSH private key is present for root"
  copy:
    src: "{{ config_libre.directory.conf }}/student-id_rsa"
    dest: "/root/.ssh/id_rsa"
    mode: 0600
    owner: "root"
  delegate_to: "{{node.name}}-env{{student.workstation|default('0')}}.{{ libre_session.id }}.{{ libre_infra.route53.domain }}"
  loop: "{{ classroom }}"
  loop_control:
    loop_var: node
    label: "{{ node.name }}"
- name: "aws : provision-post-post : student {{ student.id}} : Change hostname for student nodes"
  hostname:
    name: "{{node.name}}{{student.workstation|default('0')}}"
  become: yes
  delegate_to: "{{node.name}}-env{{student.workstation|default('0')}}.{{ libre_session.id }}.{{ libre_infra.route53.domain }}"
  loop: "{{ classroom }}"
  loop_control:
    loop_var: node
    label: "{{ node.name }}"
- name: "aws : provision-post-post : student {{ student.id}} : Update student /etc/hosts file"
  copy:
    src: /tmp/{{student.workstation|default('0')}}.hosts
    dest: /etc/hosts
  become: yes
  delegate_to: "{{node.name}}-env{{student.workstation|default('0')}}.{{ libre_session.id }}.{{ libre_infra.route53.domain }}"
  loop: "{{ classroom }}"
  loop_control:
    loop_var: node
    label: "{{ node.name }}"
- name: "aws : provision-post-post : student {{ student.id}} : Copy session {{ libre_session.id }} configuration to workstation"
  copy:
    src: "{{ config_libre.directory.conf }}/{{ r_session_config_file }}"
    dest: "{{ config_libre.directory.conf }}/{{ r_session_config_file }}"
  delegate_to: "workstation-env{{student.workstation|default('0')}}.{{ libre_session.id }}.{{ libre_infra.route53.domain }}"
- name: "aws : provision-post-post : student {{ student.id}} : Copy course {{ libre_session.course }} manifest to workstation"
  copy:
    src: "{{ r_session_dir_course }}/manifest.yml"
    dest: "{{ r_session_dir_course }}/manifest.yml"
  delegate_to: "workstation-env{{student.workstation|default('0')}}.{{ libre_session.id }}.{{ libre_infra.route53.domain }}"
- name: "aws : provision-post-post : student {{ student.id}} : Copy course {{ libre_session.course }} playbooks to workstation"
  copy:
    src: "{{ r_session_dir_course }}/playbooks/"
    dest: "{{ r_session_dir_course }}/playbooks"
  delegate_to: "workstation-env{{student.workstation|default('0')}}.{{ libre_session.id }}.{{ libre_infra.route53.domain }}"
- name: "aws : provision-post-post : Add infrastructure inventory {{config_libre.directory.conf}}/inventory in workstation"
  file:
    state: "directory"
    path: "{{config_libre.directory.conf}}/inventory"
  delegate_to: "workstation-env{{student.workstation|default('0')}}.{{ libre_session.id }}.{{ libre_infra.route53.domain }}"
- name: "aws : provision-post-post : Generate inventory {{ config_libre.directory.conf }}/inventory/local.yml"
  template:
    src: "../templates/inventory-local.j2"
    dest: "{{ config_libre.directory.conf }}/inventory/local.yml"
    mode: 0664
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"
  delegate_to: "workstation-env{{student.workstation|default('0')}}.{{ libre_session.id }}.{{ libre_infra.route53.domain }}"
- name: "aws : provision-post-post : Generate students inventory {{config_libre.directory.conf}}/inventory/students.yml"
  template:
    src: "../templates/inventory-student.j2"
    dest: "{{ config_libre.directory.conf }}/inventory/students.yml"
    mode: 0664
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"
  delegate_to: "workstation-env{{student.workstation|default('0')}}.{{ libre_session.id }}.{{ libre_infra.route53.domain }}"
