---
- name: "uninstall : libre : Remove libre-* library from {{ r_libre_dest_lib }}"
  file:
    state: absent
    path: "{{ r_libre_dest_lib }}/{{ libname }}"
  loop: "{{ r_libre_files_library }}"
  loop_control:
    loop_var: libname
- name: "uninstall : libre : Remove libre-* binary from {{ r_libre_dest_bin }}"
  file:
    state: absent
    path: "{{ r_libre_dest_bin }}/{{ binname }}"
  loop: "{{ r_libre_files_binary_all }}"
  loop_control:
    loop_var: binname
- name: "uninstall : libre : Remove auto-completion script to /etc/bash_completion.d/libre"
  file:
    state: absent
    path: /etc/bash_completion.d/libre
- name: "uninstall : libre : Remove profile script to /etc/profile.d/libre.sh"
  file:
    state: absent
    path: /etc/profile.d/libre.sh
- name: "uninstall : libre : Get previous report data"
  set_fact:
    previous_report: "{{ lookup('file', r_libre_tmp + '/' + r_libre_tmpfile) | default('') }}"
  become: no
- name: "uninstall : libre : Generate LIBRE report at {{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
  template:
    src: libre_report-uninstall.j2
    dest: "{{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
    mode: 0664
  become: no
- name: "uninstall : libre : Remove libre ansible library from {{ r_libre_dest_ansible }}"
  file:
    state: absent
    path: "{{ r_libre_dest_ansible }}"
