---
- name: "config : Config {{ config_session.type }} session type"
  include_tasks: "config/{{ config_session.type }}.yml"

- name: "config : Reload session configuration"
  include_tasks: "load/config.yml"

- name: "config : Log config action"
  include_role:
    name: libre
    tasks_from: lib/log
  vars:
    log_name: "Session  {{ config_session.type }} is configured"
    log_component: session
    log_action: config
