---
- when: not libre_install_postcheck or
            libre_install_postcheck is undefined
  block:
  - name: "install-postcheck : Training directory detail must exist"
    assert:
      that: r_libre_dir_details is defined
      msg: "Training directory detail doesn't exist. Try to re-install LIBRE Toolkit and start again this setup."

  - name: "install-postcheck : Training directory {{ config_libre.directory.base }} must exist"
    assert:
      that: r_libre_dir_details.stat.exists
      msg: "Training directory {{ config_libre.directory.base }} doesn't exist. Try to re-install LIBRE Toolkit and start again this setup."

  - name: "install-postcheck : Training course directory {{ config_libre.directory.course }} must exist"
    assert:
      that: r_libre_dir_course_details.stat.exists
      msg: "Training course directory {{ config_libre.directory.course }} doesn't exist. Try to re-install LIBRE Toolkit and start again this setup."

  - name: "install-postcheck : Training configuration directory {{ config_libre.directory.conf }} must exist"
    assert:
      that: r_libre_dir_conf_details.stat.exists
      msg: "Training configuration directory {{ config_libre.directory.conf }} doesn't exist. Try to re-install LIBRE Toolkit and start again this setup."

  - name: "install-postcheck : User libre configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_myconfile_libre }} exist"
    assert:
      that: r_libre_libre_userconf_details.stat.exists
      msg: "User libre configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_myconfile_libre }} doesn't exist"

  - name: "install-postcheck : User libre configuration is loaded"
    assert:
      that: config_libre is defined
      msg: "Libre configuration {{ r_libre_myconfile_libre }} is not loaded"

  - name: "install-postcheck : User session configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_myconfile_session }} exist"
    assert:
      that: r_libre_session_userconf_details.stat.exists
      msg: "User session configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_myconfile_session }} doesn't exist"

  - name: "install-postcheck : User session configuration is loaded"
    assert:
      that: config_session is defined
      msg: "Session configuration {{ r_libre_myconfile_session }} is not loaded"

  - name: "install-postcheck : User repository configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_myconfile_repository }} exist"
    assert:
      that: r_libre_repository_userconf_details.stat.exists
      msg: "User repository configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_myconfile_repository }} doesn't exist"

  - name: "install-postcheck : User repository configuration is loaded"
    assert:
      that: config_repository is defined
      msg: "Session configuration {{ r_libre_myconfile_repository }} is not loaded"

  - name: "install-postcheck : User infra configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_myconfile_infra }} exist"
    assert:
      that: r_libre_infra_userconf_details.stat.exists
      msg: "User infra configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_myconfile_infra }} doesn't exist"

  - name: "install-postcheck : User infra configuration is loaded"
    assert:
      that: config_infra is defined
      msg: "Session configuration {{ r_libre_myconfile_infra }} is not loaded"

- name: "install-precheck : Mark LIBRE install-postcheck as done"
  set_fact:
    libre_install_postcheck: True
