---
- name: "install-postcheck : Get {{ config_libre.directory.conf }} directory details"
  stat:
    path: "{{ config_libre.directory.conf }}"
  register: r_libre_dir_conf_details
- name: "load_config : Get user libre configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_myconfile_libre }} details"
  stat:
    path: "{{ r_libre_userconfig_dir }}/{{ r_libre_myconfile_libre }}"
  register: r_libre_libre_userconf_details
  become: no
- name: "install-postcheck : Get user session configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_myconfile_session }} details"
  stat:
    path: "{{ r_libre_userconfig_dir }}/{{ r_libre_myconfile_session }}"
  register: r_libre_session_userconf_details
  become: no
- name: "install-postcheck : Get user repository configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_myconfile_repository }} details"
  stat:
    path: "{{ r_libre_userconfig_dir }}/{{ r_libre_myconfile_repository }}"
  register: r_libre_repository_userconf_details
  become: no
- when: not libre_install_postcheck or
            libre_install_postcheck is undefined
  block:
  - name: "install-postcheck : Training directory detail must exist"
    assert:
      that: r_libre_dir_details is defined and (r_libre_dir_details.skipped is defined or r_libre_dir_details.stat is defined)
      msg: "Training directory detail doesn't exist. Try to re-install LIBRE Toolkit and start again this setup."

  - name: "install-postcheck : Training directory {{ config_libre.directory.base }} must exist"
    assert:
      that: r_libre_dir_details.skipped is defined or r_libre_dir_details.stat.exists
      msg: "Training directory {{ config_libre.directory.base }} doesn't exist. Try to re-install LIBRE Toolkit and start again this setup."
  - name: "install-postcheck : Training course directory {{ config_libre.directory.course }} must exist"
    assert:
      that: r_libre_dir_course_details.skipped is defined or r_libre_dir_course_details.stat.exists
      msg: "Training course directory {{ config_libre.directory.course }} doesn't exist. Try to re-install LIBRE Toolkit and start again this setup."
  - name: "install-postcheck : Training configuration directory {{ config_libre.directory.conf }} must exist"
    assert:
      that: r_libre_dir_conf_details.skipped is defined or r_libre_dir_conf_details.stat.exists
      msg: "Training configuration directory {{ config_libre.directory.conf }} doesn't exist. Try to re-install session and start again this setup."
  - name: "install-postcheck : Training collect directory {{ config_libre.directory.collect }} must exist"
    assert:
      that: r_libre_dir_collect_details.skipped is defined or r_libre_dir_collect_details.stat.exists
      msg: "Training collect directory {{ config_libre.directory.collect }} doesn't exist. Try to re-install session and start again this setup."

  - name: "install-postcheck : User libre configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_myconfile_libre }} exist"
    assert:
      that: r_libre_libre_userconf_details.stat.exists
      msg: "User libre configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_myconfile_libre }} doesn't exist"
  - name: "install-postcheck : User libre configuration is loaded"
    assert:
      that: config_libre is defined
      msg: "Libre configuration {{ r_libre_myconfile_libre }} is not loaded"

  - name: "install-postcheck : User session configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_myconfile_session }} exist"
    assert:
      that: r_libre_session_userconf_details.stat.exists
      msg: "User session configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_myconfile_session }} doesn't exist"
  - name: "install-postcheck : User session configuration is loaded"
    assert:
      that: config_session is defined
      msg: "Session configuration {{ r_libre_myconfile_session }} is not loaded"

  - name: "install-postcheck : User repository configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_myconfile_repository }} exist"
    assert:
      that: r_libre_repository_userconf_details.stat.exists
      msg: "User repository configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_myconfile_repository }} doesn't exist"
  - name: "install-postcheck : User repository configuration is loaded"
    assert:
      that: config_repository is defined
      msg: "Session configuration {{ r_libre_myconfile_repository }} is not loaded"

- name: "install-precheck : Mark LIBRE install-postcheck as done"
  set_fact:
    libre_install_postcheck: True
