---
#- debug: var=list_dns
#- debug: var=route53_instructor
#- fail:
  
  
#- name: "aws : provision : inventory : Generate instructor inventory {{config_libre.directory.conf}}/inventory/instructor.yml"
#  template:
#    src: "../templates/inventory-instructor.j2"
#    dest: "{{config_libre.directory.conf}}/inventory/instructor.yml"
#    mode: 0664
#    owner: "{{ r_libre_user }}"
#    group: "{{ r_libre_group }}"

- debug:
    msg: "mos"

- name: "aws : provision : inventory : Generate students inventory {{config_libre.directory.conf}}/inventory/students.yml"
  template:
    src: "../templates/inventory-students.j2"
    dest: "{{config_libre.directory.conf}}/inventory/students.yml"
    mode: 0664
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"

