---
- name: "load : Get {{ config_libre.directory.conf }}/{{ r_lab_track_current_lab_filename }} file details"
  stat:
    path: "{{ config_libre.directory.conf }}/{{ r_lab_track_current_lab_filename }}"
  register: r_lab_track_current_lab_filename_details
- name: "load : Load {{ config_libre.directory.conf }}/{{ r_lab_track_current_lab_filename }} content"
  set_fact:
    lab_current: "{{ lookup('file', config_libre.directory.conf+'/'+r_lab_track_current_lab_filename) | default(lab_default_current_lab) }}"
  when:
  - r_lab_track_current_lab_filename_details.stat.exists
  - lab_current is not defined
- name: "load : No current lab found in {{ config_libre.directory.conf }}/{{ r_lab_track_current_lab_filename }}, Set default to lab {{lab_default_current_lab}}"
  set_fact:
    lab_current: "{{lab_default_current_lab}}"
  when:
  - not r_lab_track_current_lab_filename_details.stat.exists
  - lab_current is not defined

- name: "load : Course description is loaded"
  assert:
    that: libre_course is defined
    msg: "Course description {{ r_lab_dir_course }}/manifest.yml is not loaded"

- name: "load : Find lab {{ lab_current }} in course manifest.yml"
  loop: [idn, id]
  set_fact:
    current_lab: "{{ libre_course | default({}) | json_query(qry) }}"
  vars:
    qry: 'labs[?{{ item }}==`{{ lab_current }}`] | [0]'
  when: current_lab is not defined or current_lab == "" or current_lab.id is not defined
- name: "load : Lab description is loaded"
  assert:
    that:
    - current_lab is defined
    - current_lab.id is defined
    msg: "Lab description {{ lab_current }} doesn't exist"
- name: "load : Check if lab {{lab_current}} exist"
  assert:
    that: current_lab is defined and current_lab.id is defined
    msg: "Lab {{ lab_current }} could not be found in {{ r_lab_dir_course }}/manifest.yml"
- name: "load : Set fact r_current_lab_dir to {{ r_lab_dir_course }}/{{ r_lab_dir_course_labs}}/{{  current_lab.directory | default(current_lab.id) }}"
  set_fact:
    r_current_lab_dir: "{{ r_lab_dir_course }}/{{ r_lab_dir_course_labs}}/{{ current_lab.directory | default(current_lab.id) }}"

- block:
  - name: "load : {{ r_current_lab_dir }} directory details"
    stat:
      path: "{{ r_current_lab_dir }}"
    register: r_current_lab_dir_details
  - name: "load : Check if {{ r_current_lab_dir }} directory exist"
    assert:
      that: r_current_lab_dir_details.stat.exists
      msg: "Lab {{ current_lab.name }} is defined in the manifest but the lab folder does not exists"
