---
- stat:
    path: "{{ r_current_lab_dir }}/stop.yml"
  register: r_lab_stop_file_details

# Reset pre-tasks

- name: "reset : Course description is loaded"
  assert:
    that: libre_course is defined
    msg: "Course description {{ r_lab_dir_course }}/manifest.yml is not loaded"

- name: "reset : Lab description is loaded"
  assert:
    that:
    - current_lab is defined
    - current_lab.id is defined
    msg: "Lab description {{ lab_current }} doesn't exist"

- name: "reset : Ansible lab directory {{ r_current_lab_dir }} exists"
  assert:
    that:
    - r_current_lab_dir_details is defined
    - r_current_lab_dir_details.stat.exists
    msg: "Ansible lab directory {{ r_current_lab_dir }} doesn't exist"

# Reset tasks
- name: "reset : Stop lab {{ current_lab.id }} {{ current_lab.name }}"
  include_tasks: "{{ r_current_lab_dir }}/stop.yml"
  when: r_lab_stop_file_details.stat.exists
- name: "reset : Start lab {{ current_lab.id }} {{ current_lab.name }}"
  include_tasks: "{{ r_current_lab_dir }}/start.yml"

- name: "reset : Get previous report data"
  set_fact:
    previous_report: "{{ lookup('file', r_libre_tmp + '/' + r_libre_tmpfile, errors='ignore') | default('') }}"
- name: "reset : Generate LIBRE report at {{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
  template:
    src: libre_report-reset.j2
    dest: "{{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
    mode: 0664

- name: "reset : Log reset action"
  include_role:
    name: libre
    tasks_from: lib/log
  vars:
    log_name: "Reseting lab {{ current_lab.id }} {{ current_lab.name }}"
    log_component: lab
    log_action: reset
