---
# Start pre-tasks

- name: "start : Course description is loaded"
  assert:
    that: libre_course is defined
    msg: "Course description {{ r_lab_dir_course }}/manifest.yml is not loaded"

- name: "start : Lab description is loaded"
  assert:
    that:
    - current_lab is defined
    - current_lab.id is defined
    msg: "Lab description {{ lab_current }} doesn't exist"

- name: "start : Ansible lab directory {{ r_current_lab_dir }} exists"
  assert:
    that:
    - r_current_lab_dir_details is defined
    - r_current_lab_dir_details.stat.exists
    msg: "Ansible lab directory {{ r_current_lab_dir }} doesn't exist"

- name: "start : Save the current lab id in {{ config_libre.directory.conf }}/{{ r_lab_config_current }}"
  copy:
    dest: "{{ config_libre.directory.conf }}/{{ r_lab_config_current }}"
    content: "{{ current_lab.idn }}"

# Start tasks
- name: "start : Start creating lab {{ current_lab.id }} {{ current_lab.name }}"
  include_tasks: "{{ r_current_lab_dir }}/start.yml"
- name: "start : Get previous report data"
  set_fact:
    previous_report: "{{ lookup('file', r_libre_tmp + '/' + r_libre_tmpfile) }}"
- name: "start : Generate LIBRE report at {{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
  template:
    src: libre_report-start.j2
    dest: "{{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
    mode: 0664

- name: "start : Log start action"
  include_role:
    name: libre
    tasks_from: lib/log
  vars:
    log_name: "Start lab {{ current_lab.id }} {{ current_lab.name }}"
    log_component: lab
    log_action: start
