---
# Start pre-tasks

- name: "start : Course description is loaded"
  assert:
    that: libre_course is defined
    msg: "Course description {{ r_lab_dir_course }}/manifest.yml is not loaded"

- name: "start : Course description is loaded"
  assert:
    that:
    - libre_lab is defined
    - libre_lab.id is defined
    msg: "Lab description {{ lab_current }} doesn't exist"

- name: "start : Ansible lab directory {{ r_lab_dir_course }}/{{ r_lab_dir_course_labs}}/{{ libre_lab.id }} exists"
  assert:
    that:
    - r_lab_currentlab_ansible_details is defined
    - r_lab_currentlab_ansible_details.stat.exists
    msg: "Ansible lab directory {{ r_lab_dir_course }}/{{ r_lab_dir_course_labs}}/{{ libre_lab.id }} doesn't exist"

# Start tasks

- name: "start : Get previous report data"
  set_fact:
    previous_report: "{{ lookup('file', r_libre_tmp + '/' + r_libre_tmpfile) }}"
  delegate_to: localhost

- name: "start : Start creating lab {{ libre_lab.id }} {{ libre_lab.name }}"
  include_tasks: "{{ r_lab_dir_course }}/{{ r_lab_dir_course_labs}}/{{ libre_lab.id }}/start.yml"

- name: "start : Get previous report data"
  set_fact:
    previous_report: "{{ lookup('file', r_libre_tmp + '/' + r_libre_tmpfile) }}"
  delegate_to: localhost

- name: "start : Generate LIBRE report at {{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
  template:
    src: libre_report-start.j2
    dest: "{{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
    mode: 0664
  delegate_to: localhost

- name: "start : Log start action"
  include_role:
    name: libre
    tasks_from: lib/log
  vars:
    log_name: "Start lab {{ libre_lab.id }} {{ libre_lab.name }}"
    log_component: lab
    log_action: start
