---
- name: "status : Start student status"
  include_role:
    name: student
    tasks_from: status

- name: "status : Get previous report data"
  set_fact:
    previous_report: "{{ lookup('file', r_libre_tmppath, errors='ignore') | default('') }}"
- name: "status : Generate repository report at {{ r_libre_result_file }}"
  template:
    src: libre_report-status.j2
    dest: "{{ r_libre_result_file }}"
#    owner: root
    group: "{{ r_libre_group }}"
    mode: 0666
