---
- stat:
    path: "{{ r_current_lab_dir }}/stop.yml"
  register: r_lab_stop_file_details

# Stop pre-tasks

- name: "stop : Course description is loaded"
  assert:
    that: libre_course is defined
    msg: "Course description {{ r_lab_dir_course }}/manifest.yml is not loaded"

- name: "stop : Course description is loaded"
  assert:
    that:
    - current_lab is defined
    - current_lab.id is defined
    msg: "Lab description {{ lab_current }} doesn't exist"

- name: "stop : Ansible lab directory {{ r_current_lab_dir }} exists"
  assert:
    that:
    - r_current_lab_dir_details is defined
    - r_current_lab_dir_details.stat.exists
    msg: "Ansible lab directory {{ r_current_lab_dir }} doesn't exist"

# Stop tasks
- name: "stop : Cleaning lab {{ current_lab.id }} {{ current_lab.name }}"
  include_tasks: "{{ r_current_lab_dir }}/stop.yml"
  when: r_lab_stop_file_details.stat.exists
- name: "stop : Get previous report data"
  set_fact:
    previous_report: "{{ lookup('file', r_libre_tmp + '/' + r_libre_tmpfile) }}"
- name: "stop : Generate LIBRE report at {{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
  template:
    src: libre_report-stop.j2
    dest: "{{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
    mode: 0664
- name: "stop : Log stop action"
  include_role:
    name: libre
    tasks_from: lib/log
  vars:
    log_name: "Stop lab {{ current_lab.id }} {{ current_lab.name }}"
    log_component: lab
    log_action: stop

- name: "stop : {{ config_libre.directory.conf }}/{{ r_lab_track_current_lab_filename }} doesn't exists"
  file:
    state: absent
    path: "{{ config_libre.directory.conf }}/{{ r_lab_track_current_lab_filename }}"