---
# Stop pre-tasks

- name: "stop : Course description is loaded"
  assert:
    that: libre_course is defined
    msg: "Course description {{ r_lab_dir_course }}/manifest.yml is not loaded"

- name: "stop : Course description is loaded"
  assert:
    that:
    - libre_lab is defined
    - libre_lab.id is defined
    msg: "Lab description {{ lab_current }} doesn't exist"

- name: "stop : Ansible lab directory {{ r_lab_dir_course }}/{{ r_lab_dir_course_labs}}/{{ libre_lab.id }} exists"
  assert:
    that:
    - r_lab_currentlab_ansible_details is defined
    - r_lab_currentlab_ansible_details.stat.exists
    msg: "Ansible lab directory {{ r_lab_dir_course }}/{{ r_lab_dir_course_labs}}/{{ libre_lab.id }} doesn't exist"

# Stop tasks

- name: "stop : Get previous report data"
  set_fact:
    previous_report: "{{ lookup('file', r_libre_tmp + '/' + r_libre_tmpfile) }}"
  delegate_to: localhost

- name: "stop : Cleaning lab {{ libre_lab.id }} {{ libre_lab.name }}"
  include_tasks: "{{ r_lab_dir_course }}/{{ r_lab_dir_course_labs}}/{{ libre_lab.id }}/stop.yml"

- name: "stop : Get previous report data"
  set_fact:
    previous_report: "{{ lookup('file', r_libre_tmp + '/' + r_libre_tmpfile) }}"
  delegate_to: localhost

- name: "stop : Generate LIBRE report at {{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
  template:
    src: libre_report-stop.j2
    dest: "{{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
    mode: 0664
  delegate_to: localhost

- name: "stop : Log stop action"
  include_role:
    name: libre
    tasks_from: lib/log
  vars:
    log_name: "Stop lab {{ libre_lab.id }} {{ libre_lab.name }}"
    log_component: lab
    log_action: stop
