---
- name: "load_report : Touch report file {{ r_libre_tmp }}/{{ r_libre_tmpfile  }}"
  file:
    path: "{{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
    state: touch
    owner: root
    group: "{{ r_libre_goup }}"
    mode: 0666
