## LIBRE role default variables

# Configure uninstall to deep remove all content (facts, training dir and libre tools)
r_libre_uninstall_deep: "{{ libre_uninstall_deep | default(False) | bool }}"
# Used to force upgrading libre lib
r_libre_force_upgrade: "{{ libre_force_upgrade | default(False) | bool }}"

# Set LIBRE destination directory for LIBRE library
r_libre_dest_lib: "{{ libre_dest_lib | default('/usr/local/lib') }}"
# Set LIBRE destination directory for LIBRE binary
r_libre_dest_bin: "{{ libre_dest_bin | default('/usr/local/bin') }}"
# Set LIBRE destination directory for ansible content
r_libre_dest_ansible: "{{ libre_dest_ansible | default('/usr/local/lib/libre-ansible') }}"

# Config file for hardware
r_libre_config_file_hw: "{{ libre_config_file_hw | default('hardware.json') | string }}"

# Default user for course content
r_libre_user: "{{ libre_user | default('instructor') | string }}"
# Default user for course content
r_libre_group: "{{ libre_group | default('libre') | string }}"
# Personal home directory where configuration is stored
r_libre_userconfig_dir: "{{ libre_userconfig_dir | default('~/.libre') | string }}"
# Config file for LIBRE
r_libre_myconfile_libre: "{{ libre_myconfile_libre | default('config.yml') | string }}"
# Config file for session
r_libre_myconfile_session: "{{ libre_myconfile_session | default('session.yml') | string }}"
# Config file for infrastructure
r_libre_myconfile_infra: "{{ libre_myconfile_infra | default('infra.yml') | string }}"
# Config file for repository
r_libre_myconfile_repository: "{{ libre_myconfile_repository | default('repository.yml') | string }}"
# Default directory used for delivering training
r_libre_dir: "{{ training_dir | default('/libre') | string }}"
# Course directory used for delivering training
r_libre_dir_course: "{{ training_dir_course | default('/libre/course') | string }}"
# Configuration directory used for delivering training
r_libre_dir_conf: "{{ training_dir_conf | default('/libre/conf') | string }}"
# Collect directory used for collecting training activity
r_libre_dir_collect: "{{ training_dir_collect | default('/libre/collect') | string }}"
# Set LIBRE source temporary directory for exchange with libre command line
r_libre_tmp: "{{ libre_tmp | default('/tmp') | string }}"
# Set LIBRE filename used as temporary buffer to send content to the LIBRE command line
r_libre_tmpfile: "{{ libre_tmpfile | default('libre.txt') | string }}"

# Default config_libre structure
r_libre_libre_userconf_default:
  application:
    type: "{{ libre_type | default('instructor') | string }}"
    version: "{{ libre_version | default('0.5.28') | string }}"
    verbose: "{{ libre_verbose | default(True) | bool }}"
    debug: "{{ libre_debug | default(True) | bool }}"
    source:
      repo: "{{ libre_source_url | default('https://github.com/startxfr/libre') }}"
      branch: "{{ libre_source_branch | default('master') }}"
      base: "{{ libre_source_base | default('/') }}"
      tmp: "{{ libre_source_tmp | default('/tmp/libre') }}"
  directory:
    base: "{{ r_libre_dir }}"
    course: "{{ r_libre_dir_course }}"
    collect: "{{ r_libre_dir_collect }}"
# Default config_session structure
r_libre_session_userconf_default:
  type: "{{ libre_session_type | default('sample') | string }}"
  gapi: "{{ libre_session_gapi | default('https://script.google.com/macros/s/XXXXXXX_DOCKEY_XXXXXXXXXXXXXXXXXX/exec') | string }}"
# Default config_infra structure
r_libre_infra_userconf_default:
  default: "{{ libre_infra_type | default('self') | string }}"
  self: 
    type: "self"
    network:
      dns: "{{ infra_self_dns_zone | default('classroom.example.com') | string }}"
      associated_ip: "{{ infra_associated_ip | default('127.0.0.1') | string }}"
  prem: 
    type: "prem"
    network:
      dns: "{{ infra_prem_dns_zone | default('training.example.com') | string }}"
    ssh:
      privateKey_file: "{{ infra_prem_ssh_private_key_file | default('~/my-ssh-key.pem') | string }}"
      user: "{{ infra_prem_ssh_user | default('root') | string }}"
  aws: 
    type: "aws"
    auth:
      access_key: "{{ infra_aws_access_key | default(false) }}"
      secret_key: "{{ infra_aws_secret_key | default(false) }}"
    route53:
      zone: "{{ infra_aws_route53_dns_zone | default('startx.fr') | string }}"
      domain: "{{ infra_aws_public_dns_zone | default('libre.startx.fr') | string }}"
    ec2:
      region: "{{ infra_aws_region | default('eu-west-1') | string }}"
      type: "{{ infra_aws_instance_type | default('t2.micro') | string }}"
      image: "{{ infra_aws_image | default('ami-3548444c') | string }}"
      instance_nb: "{{ infra_aws_instance_nb | default(1) | int }}"
    ssh:
      keyname: "{{ infra_aws_key_name | default('ssh-key') | string }}"
      privateKey_file: "{{ infra_aws_ssh_private_key_file | default('~/.ssh/id_rsa') | string }}"
      user: "{{ infra_aws_ssh_user | default('centos') | string }}"
# Default config_repository structure
r_libre_repository_userconf_default:
  url: "{{ repository_url | default('https://github.com/startxfr/libre') | string }}"
  branch: "{{ repository_branch | default('master') | string }}"
  base: "{{ repository_base | default('/courses-samples') | string }}"
  local: "{{ repository_local | default('/var/local/libre.repo') | string }}"

# Default libre_hardware structure
r_libre_minhw:
  architecure: "{{ libre_minhw_architecure | default('x86_64') | string }}"
  cpu:
    physical: "{{ libre_minhw_cpu_physical | default(1) | int }}"
    cores: "{{ libre_minhw_cpu_cores | default(1) | int }}"
    vcpus: "{{ libre_minhw_cpu_vcpus | default(2) | int }}"
  memory:
    total: "{{ libre_minhw_memory_total | default(4096) | int }}"
    free: "{{ libre_minhw_memory_free | default(1024) | int }}"
  storage:
    percent: "{{ libre_minhw_storage_percent | default(20) | int }}"
    capacity: "{{ libre_minhw_storage_capacity | default(4096) | int }}"

# List of LIBRE library files
r_libre_files_library:
  - "libre-chapter"
  - "libre-chapter.txt"
  - "libre-infra"
  - "libre-infra.txt"
  - "libre-core"
  - "libre-instructor"
  - "libre-instructor.txt"
  - "libre-repository"
  - "libre-repository.txt"
  - "libre-lab"
  - "libre-lab.txt"
  - "libre-session"
  - "libre-session.txt"
  - "libre-student"
  - "libre-student.txt"

# List of LIBRE binary files for all installation
r_libre_files_binary_all:
  - "libre-chapter"
  - "libre-infra"
  - "libre-instructor"
  - "libre-repository"
  - "libre-lab"
  - "libre-session"
  - "libre-student"

# List of LIBRE binary files for instructor
r_libre_files_binary_instructor:
  - "libre-chapter"
  - "libre-infra"
  - "libre-instructor"
  - "libre-repository"
  - "libre-lab"
  - "libre-session"

# List of LIBRE binary files for student
r_libre_files_binary_student:
  - "libre-lab"
  - "libre-student"
