## LIBRE role default variables

do: load

# Configure uninstall to deeply remove all content 
# uninstall libre will remove lib, bin, playbooks, repository and training dir (after backup if set)
# deep uninstall will also remove user config directory
libre_uninstall_deep: False
# Used to force upgrading LIBRE lib
libre_force_upgrade: False

# Set LIBRE destination directory for LIBRE library
libre_dest_lib: '/usr/local/lib'
# Set LIBRE destination directory for LIBRE binary
libre_dest_bin: '/usr/local/bin'
# Set LIBRE destination directory for ansible content
libre_dest_ansible: '{{ libre_dest_lib }}/libre-ansible'

# Config file for hardware
libre_config_file_hw: 'hardware.json'

# Default user for course content
libre_user: 'instructor'
# Default user for course content
libre_group: 'libre'
# Personal home directory where configuration is stored
libre_userconfig_dir: '~/.libre'
# Config file for LIBRE
libre_myconfile_libre: 'config.yml'
# Config file for repository
libre_myconfile_repository: 'repository.yml'
# Default directory used for delivering training
training_dir: '/usr/share/libre'
# Course directory used for delivering training
training_dir_course: '{{ training_dir }}/course'
# Configuration directory used for delivering training
training_dir_conf: '{{ training_dir }}/conf'
# Collect directory used for collecting training activity
training_dir_collect: '{{ training_dir }}/collect'
# Set LIBRE source temporary directory for exchange with LIBRE command line
libre_tmp: '/tmp'
# Set LIBRE filename used as temporary buffer to send content to the LIBRE command line
libre_tmpfile: 'libre.txt'

# Default config_LIBRE structure
libre_type: 'instructor'
libre_version: '0.0.1-devel'
libre_verbose: True
libre_debug: True
libre_source_url: 'https://github.com/startxfr/libre'
libre_source_branch: 'master'
libre_source_base: '/'
libre_source_tmp: '{{ libre_tmp }}/libre'
# Default config_repository structure
repository_url: 'https://github.com/startxfr/libre'
repository_branch: 'master'
repository_base: '/courses-samples'
repository_local: '/var/local/libre.repo'

# Default libre_hardware structure
libre_minhw_architecure: 'x86_64'
libre_minhw_cpu_physical: 1
libre_minhw_cpu_cores: 1
libre_minhw_cpu_vcpus: 2
libre_minhw_memory_total: 4096
libre_minhw_memory_free: 1024
libre_minhw_storage_percent: 20
libre_minhw_storage_capacity: 4096
