id: LIBRE-dev01
version: 0.0.1
provider: ADL
familly: Libre
name: Libre-instructor webapp developement course example
desc: Webapp developement course example used for testing libre instructor libre web-application
schedule:
  days: 1
  hours: 7
  start: "9am"
  end: "5pm"
  timetable:
    - day: 1
      hours: 6
      start: "10am"
      end: "5pm"
    - day: 2
      hours: 7
      start: "9am"
      end: "5pm"
    - day: 3
      hours: 7
      start: "9am"
      end: "5pm"
    - day: 4
      hours: 7
      start: "9am"
      end: "5pm"
    - day: 4
      hours: 7
      start: "9am"
      end: "5pm"
url: 
  public: https://github.com/startxfr/libre
  course: https://github.com/startxfr/libre
content: 
  - id: "1"
    name: "Chapter I example"
    type: chapter
    time: 99
    content:
      - id: "1.1"
        name: "Sub-chapter I.1 example"
        type: section
        time: 1
      - id: "1.2"
        name: "Sub-chapter I.2 example"
        type: section
        time: 2
      - id: "1.3"
        name: "Sub-chapter I.3 lab"
        type: lab
        time: 3
        lab_id: 1
  - id: "2"
    name: "Chapter II example"
    type: chapter
    time: 210
    content:
      - id: "2.1"
        name: "Sub-chapter II.1 example"
        type: section
        time: 1
      - id: "2.2"
        name: "Sub-chapter II.2 lab"
        type: lab
        time: 2
        lab_id: 2
labs:
  - id: 1
    idn: "lab-1.3"
    name: "Sub-chapter I.3 lab"
    desc: lab description for Sub-chapter I.3 lab
    time: 3
  - id: 2
    idn: "lab-2.2"
    name: "Sub-chapter II.2 lab"
    desc: lab description for Sub-chapter II.2 lab
    time: 2