---
- name: "Upgrade training repository environment on instructor"
  hosts: 'instructor'
  gather_facts: true

  roles:
    - { role: repository, do: load }
    - { role: repository, do: upgrade, become: yes }
