---
- name: "status : Start infrastructure status"
  include_role:
    name: session
    tasks_from: status
- name: "status : Get previous report data"
  set_fact:
    previous_report: "{{ lookup('file', r_libre_tmp + '/' + r_infra_tmpfile) | default('') }}"
  delegate_to: localhost
- name: "status : Status of AWS infrastructure"
  include_tasks: "aws/status.yml"
  when: libre_infra.type == 'aws'
- name: "status : Status of On-Premise infrastructure"
  include_tasks: "prem/status.yml"
  when: libre_infra.type == 'prem'
- name: "status : Status of Self-Hosted infrastructure"
  include_tasks: "self/status.yml"
  when: libre_infra.type == 'self'